export type Destination = { slug: string; name: string; country: string; code: string; headout?: string; gyg?: string };

export const destinations: Destination[] = [
  { slug: 'london', name: 'London', country: 'United Kingdom', code: 'GB', headout: 'LONDON', gyg: '57' },
  { slug: 'edinburgh', name: 'Edinburgh', country: 'United Kingdom', code: 'GB', headout: 'EDINBURGH' },
  { slug: 'lisbon', name: 'Lisbon', country: 'Portugal', code: 'PT', headout: 'LISBON' },
  { slug: 'porto', name: 'Porto', country: 'Portugal', code: 'PT', headout: 'PORTO' },
  { slug: 'madeira', name: 'Madeira', country: 'Portugal', code: 'PT', headout: 'FUNCHAL' },
  { slug: 'barcelona', name: 'Barcelona', country: 'Spain', code: 'ES', headout: 'BARCELONA', gyg: '45' },
  { slug: 'madrid', name: 'Madrid', country: 'Spain', code: 'ES', headout: 'MADRID' },
  { slug: 'tenerife', name: 'Tenerife', country: 'Spain', code: 'ES', headout: 'TENERIFE', gyg: '2603' },
  { slug: 'paris', name: 'Paris', country: 'France', code: 'FR', headout: 'PARIS', gyg: '42' },
  { slug: 'rome', name: 'Rome', country: 'Italy', code: 'IT', headout: 'ROME', gyg: '33' },
  { slug: 'venice', name: 'Venice', country: 'Italy', code: 'IT', headout: 'VENICE' },
  { slug: 'florence', name: 'Florence', country: 'Italy', code: 'IT', headout: 'FLORENCE' },
  { slug: 'athens', name: 'Athens', country: 'Greece', code: 'GR', headout: 'ATHENS', gyg: '91' },
  { slug: 'amsterdam', name: 'Amsterdam', country: 'Netherlands', code: 'NL', headout: 'AMSTERDAM', gyg: '59' },
  { slug: 'berlin', name: 'Berlin', country: 'Germany', code: 'DE', headout: 'BERLIN' },
  { slug: 'prague', name: 'Prague', country: 'Czech Republic', code: 'CZ', headout: 'PRAGUE' },
  { slug: 'dublin', name: 'Dublin', country: 'Ireland', code: 'IE', headout: 'DUBLIN' },
  { slug: 'dubai', name: 'Dubai', country: 'United Arab Emirates', code: 'AE', headout: 'DUBAI', gyg: '173' },
  { slug: 'new-york', name: 'New York', country: 'United States', code: 'US', headout: 'NEW_YORK', gyg: '16' },
  { slug: 'las-vegas', name: 'Las Vegas', country: 'United States', code: 'US', headout: 'LAS_VEGAS', gyg: '67' },
  { slug: 'orlando', name: 'Orlando', country: 'United States', code: 'US', headout: 'ORLANDO' },
  { slug: 'tokyo', name: 'Tokyo', country: 'Japan', code: 'JP', headout: 'TOKYO', gyg: '193' },
  { slug: 'bangkok', name: 'Bangkok', country: 'Thailand', code: 'TH', headout: 'BANGKOK' },
  { slug: 'singapore', name: 'Singapore', country: 'Singapore', code: 'SG', headout: 'SINGAPORE' },
  { slug: 'marrakech', name: 'Marrakech', country: 'Morocco', code: 'MA', headout: 'MARRAKESH' },
  { slug: 'cape-town', name: 'Cape Town', country: 'South Africa', code: 'ZA', headout: 'CAPE_TOWN' },
  { slug: 'sydney', name: 'Sydney', country: 'Australia', code: 'AU' },
  { slug: 'reykjavik', name: 'Reykjavik', country: 'Iceland', code: 'IS' },
  { slug: 'copenhagen', name: 'Copenhagen', country: 'Denmark', code: 'DK' },
  { slug: 'bali', name: 'Bali', country: 'Indonesia', code: 'ID' },
];

export const countries = Array.from(new Set(destinations.map((item) => item.country)));
